### ISSUE TITLE
Expect more detailed step by step tutorials

### ISSUE THREAD

**Issue by 1939938853** [ChenLiu-1996/CUTS#1]
Hello,

Thank you for sharing this great work. As a newbie, I really expect more detailed step by step tutorials. 

1. For training the convolutional encoder, how to prepare the dataset?  Maybe I can use a labeling tool, like the one[ here](https://github.com/scalabel/scalabel),  to label the interested object on the image? 
2. To be able to run the test it seems a model weights file is needed in Checkpoints folder?

Thanks

**Comment by ChenLiu-1996** [comment]
Thank you for your interest. We will work on improving the tutorial as you suggested.

A few things to state before you start.
1. The method proposed does not require supervision from the labels during training, so in theory we shall not ask for labels besides during quantitative evaluation --- in response to your issue, **we have just put together a pipeline that allows for training on your custom dataset without labels**.
2. Diffusion condensation for unsupervised multi-scale segmentation can get very time consuming when the image size gets larger. We recommend 128x128 at the moment (configurable in your Dataset class, see instructions in Readme).

As for your questions:
1. For preparing the dataset, you can take a look at the dataset loading examples in `src/datasets` and see how the data is usually loaded. Afterall, we are expecting a set of images and labels of matching sizes, where the labels are binary (e.g., `src/datasets/retina.py`) or multi-class (e.g., `src/datasets/berkeley_natural_images.py`), and other than that it does not matter what labeling tool you use. Then you need to write your own dataset loader under `src/datasets/***.py` and make sure it's included in `src/data_utils/prepare_dataset.py`. **We will try to include a better tutorial for this.** Again, due to the latest update, you don't need to provide the labels.
2. Yes. If you are speaking of testing on your own dataset, then you need to train your model yourself -- this method is highly dataset-specific. Once you train your model, the model weights will automatically appear in the `checkpoints` folder.

**Comment by ChenLiu-1996** [comment]
**UPDATE**

We have just **provided support for training on your custom dataset, with or without labels**. We have also added the relevant sections in the Readme. Please let us know if you run into any issue.

**Comment by 1939938853** [comment]
Thank you! I'll try.
